name: Generate Contribution Arcade

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  games:
    runs-on: ubuntu-latest
    steps:
      - uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          games: 'pacman,breakout'

      - uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update contribution arcade"
          default_author: github_actions
